### ISSUE TITLE
Which API is being used for the chat bot?

### ISSUE THREAD

**Issue by ribaricplusplus** [ezzcodeezzlife/programming-helper.com#3]
Hey there,

I'm just creating this issue as a way to ask a question.

I'm curious, how does the chat bot work? Is it GPT3? What is being used in the backend for that?

**Comment by ezzcodeezzlife** [comment]
its using the https://openai.com/api/ 

you can check it out at https://beta.openai.com/docs/

here you can here see how this repo uses this api at in the chat function [/pages/api/examples/chat.ts](https://github.com/ezzcodeezzlife/programming-helper.com/blob/master/pages/api/examples/chat.ts)

**Comment by ribaricplusplus** [comment]
Thank you for the answer! Really mind blowing how good it is.
